# Name of website
title: Emily Garceau

# Name in footer
author: Emily Garceau

# Social network links in footer
social-network-links:
  email: "garceauemily@gmail.com"
  email: "egarcea@g.clemson.edu"
  linkedin: "www.linkedin.com/in/emily-garceau"
  
